### ISSUE TITLE
Combinar en el documento existente: { merge: true }

### ISSUE THREAD

**Issue by JovannyCO** [ngocbd/loopback4-connector-firestore#1]
# ¿Es posible usar la opción { merge: true }?
https://firebase.google.com/docs/firestore/manage-data/add-data#set_a_document

```node
const cityRef = db.collection('cities').doc('BJ');

const res = await cityRef.set({
  capital: true
}, { merge: true });
```

**Comment by ngocbd** [comment]
```javascript
it('Should Merge attributes for a model instance', done => {
		Customer.replaceById(
			customer1.id,
			{ cities: ['Hanoi','Danang'] },
			{ validate: true },
			(err, customer) => {
				customer.should.have.property('cities').with.lengthOf(2);
				done(err);
			}
		);
	});
```
I publish a new version with test case "Merge attributes" so you can use replaceById for the same effect "merge: true"

**Comment by JovannyCO** [comment]
Muchas gracias... Yo utilizo merge con otro alcance, así ahorro tiempo. Voy a estudiar el caso y te lo comparto.
